#+title: Keeping warm during winter in New England
#+DATE: 2018-09-27

If you are new to Amherst or New England, or new to the cold weather, and interested in knowing more about winter clothing and survival, I find [[https://www.reddit.com/r/LifeProTips/comments/3u9el0/lpt_staying_warm_and_safe_this_winter_advice_from/][this reddit tip]] very useful.

It does not have information for keeping kids warm. So I intend to share my experience for keeping kids warm when you go outdoors.

For my family, most of the outdoor time was walking down to and from the bus stop, and waiting for the bus. If you have a car, you may find many of these tips overreaching. I spent a lot of time searching for Internet resources in the previous years and found only [[http://www.yale.edu/icenter/images/surviving_winter.pdf][one good resource from Yale University]] which seems to have been removed. Here is a copy from [[https://web.archive.org/web/20160421073953/http://www.yale.edu/icenter/images/surviving_winter.pdf][archive.org]] 

Toddlers and kids younger than 3 years won't know if they are cold.
When kids are cold, they would be drowsy, lethargic, and/or cranky. Another symptom is a sudden runny nose. Shivering may be an extreme symptom in kids.

Mittens are better than gloves for kids. They may not be able to hold things like toys or bags with their hand. The fingers keep each other warm. Mittens should be long enough to get covered by the outer jackets' sleeves.

A woolen hat is better than using only the hoods of jackets. If you have a pair of goggles for kids, they can help beat the sun glare reflecting off the snow on sunny days and possibly avoiding snow blindness. They also help in reducing wind and cold exposure to eyes and skin. Kids find goggles annoying if they have not practiced using it.

Kids feet feel warmer if two socks are worn in each feet - one over another. Cotton socks should be strictly avoided. Boots are necessary in snow. Since boots are heavier than sneakers, kids need to practice walking in boots. Else they will hate boots.

Pants should be long enough to get tucked inside the boots. If possible the lower body thermal inner-wear should be tucked inside the socks too.
Thermal inner-wear for lower body is better than just a fleece lined pant. Changing a soiled diaper will be take longer time than right now.

Shirts tucked inside pants keep the body warmer than otherwise.

In general, getting each kid ready with multiple jackets, mittens, multiple socks and boots will take longer than you think if this is your first winter. So start early or be prepared to be delayed for your schedules. Try to measure time taken to get ready and improvise everyday.
Train your children to understand and communicate (not only to the parents but also to the teacher, care giver, baby sitter) if they are feeling cold

Both kids and adults will not feel thirsty to drink adequate water. Lower water intake decreases capacity of body to self-regulate internal temperature. Also, be aware of possibility of heat stroke or heat exhaustion in cold weather due to excessive warm clothing.

Learn about frost bite so that you can identify it and react correctly. I had seen parents pour hot water on their child's hands when the child had complained her fingers were too cold, numb and hurting. It may not be the right way. This causes burns. The sensation of the limbs are absent and there is no trigger for reflex action to withdraw from the hot water.

The weather forecast of Amherst is far more accurate that what I had experienced in my hometown. Please try to understand the technical words like blizzard, snowstorm, black ice, etcetera so that you understand the warnings correctly. Last year the first real snow was after the new year's day. December had only one small insignificant snow fall.

Buying winter clothing need not be expensive. Retailers will try to promote the most profitable brands and material types. If you feel you don't have adequate winter clothing for your family, and you need tips on what to do, email me on my university email address. Search me up on the people finder.

As a concluding note, I would like to thank the gentleman, [[https://en.wikipedia.org/wiki/Polar_fleece#History][Aaron Feuerstein, who declined to patent Polar fleece]], thus enabling any vendor to produce it and making it affordable to all of us to stay warm..
