#+TITLE: Super Powers
#+DATE: 2020-06-12


Humans have been obsessed with superheroes since ages. The current superheroes depicted in movies and comics belonging to the DC universe and the Marvel universe are a subset of the superheroes known to us through history. Greek mythology has given us with superheroes like Atlas and Heracles. Heracles is recognized as Hercules in Roman mythology. Germanic mythology gave us Thor. Religion have given us individuals with a wide range of supernatural powers, giving us someone to look up to. 

We consider heroes as superheroes since they possess superpowers -- powers beyond the reach of the ordinary people. Powers are supernatural because they defy the known laws of physics -- the laws that we mortals have to obey. We may overlook powers that real people obtain, by pure hard work and perseverance. The person who can run at the fastest speed, the person who can lift the heaviest weight, the person who can calculate arithmetic the quickest all have superpowers. And then there are also those around us who can do stuff that most of us have surrendered. 

1. Ability to consistently sleep early and wake up early
2. Ability to sustain complete and absolute focus, for long periods, on the task at hand.
3. Ability to recognize emotions and empathize with fellow men & women.
4. Ability to be on-time every single time for all appointments.
5. Ability to plan hour, day, week, month, year, decade, life.
6. Ability to manage your workplace supervisor.
7. Ability to maintain a healthy lifestyle over the entire lifespan.
8. Ability to calm down crying and fussy infants and toddlers.
9. Ability to discard grudges and emotional baggage.
10. Ability to manage emotions at all times.
11. Ability to selflessly care for dependents.
12. Ability to communicate and negotiate.
13. Ability to learn new skills.
14. Ability to learn from others' mistakes.
15. Ability to make and keep new friends.
16. Ability to ...

This list will remain incomplete. 

There are many superpowers possible. These are superpowers because few people have them. These superpowers have nothing to do with anyone's career, age, gender, nationality. They are not handed over to you by someone else. No one is born with them. People wielding these superpowers have made sustained conscious efforts to master them and make it part of their daily habits and routines. 

Cheers to all ordinary people never giving up on their attempts to acquire superpowers.
